services:
  restaurant-api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGO_URI=mongodb+srv://harshamalvishwajith:200209401591@cluster0.qz6lguv.mongodb.net/restaurantdb?retryWrites=true&w=majority
      - MONGO_URI_BACKUP=mongodb+srv://harshamalvishwajith:200209401591@cluster0.qz6lguv.mongodb.net/restaurantdb_backup?retryWrites=true&w=majority
      - KAFKA_BROKER=kafka:9092
    networks:
      - kafka_network

networks:
  kafka_network:
    external: true
    name: kafka_default
