# version: "3"
# services:
#   delivery-service:
#     build: ./delivery-service-main
#     ports:
#       - "3000:3000"
#     environment:
#       - NODE_ENV=development

#   map-service:
#     build: ./map-service
#     ports:
#       - "3001:3001"
#     environment:
#       - NODE_ENV=development
#     env_file:
#       - ./map-service/.env

#   kafka:
#     image: "bitnami/kafka:latest"
#     container_name: "kafka"
#     ports:
#       - "9092:9092"
#     environment:
#       - KAFKA_CFG_NODE_ID=1
#       - KAFKA_CFG_PROCESS_ROLES=broker,controller
#       - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
#       - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
#       - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
#       - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
#       - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
#       - ALLOW_PLAINTEXT_LISTENER=yes

version: "3"
services:
  kafka:
    image: "bitnami/kafka:latest"
    container_name: "kafka"
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - ALLOW_PLAINTEXT_LISTENER=yes

  delivery-service:
    build: ./delivery-service-main
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - KAFKA_BROKER=kafka:9092
    env_file:
      - ./delivery-service-main/.env
    depends_on:
      - kafka

  map-service:
    build: ./map-service
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - KAFKA_BROKER=kafka:9092
    env_file:
      - ./map-service/.env
    depends_on:
      - kafka
