services:
  menuservice:
    build: .
    container_name: menuservice_container
    ports:
      - "5081:5081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoDbSettings__ConnectionString=mongodb+srv://harshamalvishwajith:200209401591@cluster0.qz6lguv.mongodb.net/MenuDb?retryWrites=true&w=majority
      - MongoDbSettings__DatabaseName=MenuDb
      - ASPNETCORE_URLS=http://+:7046
      - KAFKA_BROKER=kafka:9092
      - KAFKA_TOPIC=menu-events
    networks:
      - backend
      - kafka_default

networks:
  backend:
    driver: bridge
  kafka_default:
    external: true
